---
- name: create admin group "admins"
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid }}"
  with_items:
    - "{{ admin_group }}"
  tags:
    - user_mgmnt

- name: Allow sudo for admins group
  copy:
    content: "%admins ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/admins
    mode: 0600
  tags:
    - user_mgmnt

- name: User Configuration
  include_tasks: user.yml
  with_items:
    - "{{ users }}"
  tags:
    - user_mgmnt
