---
- name: Base config
  hosts: dell_home_server
  gather_facts: true
  become: true
  become_user: root

  pre_tasks:
    - action: ping
  
  tasks:
    - import_role:
        name: user_mgmnt
        tasks_from: main.yml