---
- name: Base config
  hosts: dell
  gather_facts: true
  become: true
  become_user: root

  pre_tasks:
    - action: ping
  
  tasks:
    - name: Print Facts
      ansible.builtin.debug:
        var: ansible_facts
    - import_role:
        name: postgresql
        tasks_from: main.yml